'use client';

import { ArrowRight, Award, Clock, ShieldCheck, Star } from 'lucide-react';
import { useDojo } from '@/context/DojoContext';
import { GradoProgress } from '../dojo/GradoProgress';
import { KataBadge } from '../dojo/KataBadge';
import { buildKataStudent } from '../dojo/studentKataModule';

export function StudentDashboardView() {
  const { activeStudent, activeStudentProgress, setCurrentRoute } = useDojo();
  const required = activeStudentProgress.katas.map((item) => item.kata);
  const student = buildKataStudent(activeStudent, activeStudentProgress.katas, activeStudentProgress.currentRank?.name ?? 'Grado actual', activeStudentProgress.currentRank?.beltColor ?? '#22d3ee', activeStudentProgress.nextRank?.name ?? 'Siguiente grado');
  const practiceKatas = activeStudentProgress.katas.filter((item) => item.status === 'EN_PRACTICA');
  const totalHours = student.katasProgress?.reduce((sum, item) => sum + item.practiceHours, 0) ?? 0;
  const scores = student.katasProgress?.flatMap((item) => item.score === undefined ? [] : [item.score]) ?? [];
  const averageScore = scores.length ? (scores.reduce((sum, score) => sum + score, 0) / scores.length).toFixed(1) : 'Sin nota';

  return <main className="space-y-5"><section className="flex flex-col gap-4 rounded-lg border border-neutral-800 bg-[#161b22] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full border-2 border-cyan-500/50 bg-cyan-500/10 text-lg font-bold text-cyan-200">{student.name.split(' ').map((name) => name[0]).slice(0, 2).join('')}</div><div><p className="text-xs text-cyan-400">Karateka · {student.matricula}</p><h1 className="text-xl font-bold text-white">{student.name}</h1><p className="text-sm text-neutral-400">{student.rankName}</p></div></div><div className="flex items-center gap-2 text-sm text-neutral-300"><span className="h-4 w-14 rounded-sm border border-white/30" style={{ backgroundColor: student.beltColor }} />Cinturón actual</div></section><GradoProgress student={student} requiredKatas={required} /><section className="grid gap-3 sm:grid-cols-3">{[{ icon: Clock, label: 'Horas de tatami', value: `${totalHours} h`, color: 'text-amber-400' }, { icon: ShieldCheck, label: 'Asistencias del mes', value: `${student.attendancesCount} / ${student.targetAttendances}`, color: 'text-cyan-400' }, { icon: Star, label: 'Promedio en katas', value: averageScore, color: 'text-emerald-400' }].map(({ icon: Icon, label, value, color }) => <div key={label} className="rounded-lg border border-neutral-800 bg-[#161b22] p-4"><Icon className={`h-5 w-5 ${color}`} /><p className="mt-3 text-xs text-neutral-400">{label}</p><p className="mt-1 text-lg font-bold text-white">{value}</p></div>)}</section><section className="rounded-lg border border-neutral-800 bg-[#161b22] p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold text-white">Próximas katas a evaluar</h2><p className="mt-1 text-sm text-neutral-400">Katas que ya están en tu práctica activa.</p></div><Award className="h-6 w-6 text-amber-400" /></div><div className="mt-4 space-y-2">{practiceKatas.length ? practiceKatas.map((item) => <div key={item.kata.id} className="flex items-center justify-between rounded-md bg-[#0d1117] p-3"><div><p className="text-sm font-semibold text-white">{item.kata.name}</p><p className="text-xs text-neutral-500">{item.kata.japaneseName}</p></div><KataBadge status={item.status} /></div>) : <p className="rounded-md bg-[#0d1117] p-4 text-sm text-neutral-400">No tienes katas en práctica actualmente.</p>}</div><button type="button" onClick={() => setCurrentRoute('student-katas')} className="mt-4 inline-flex items-center gap-1.5 text-sm font-bold text-cyan-300 hover:text-cyan-100">Ver mi catálogo de katas <ArrowRight className="h-4 w-4" /></button></section></main>;
}